version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.32
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQL_SERVER_PORT:$MYSQL_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_SERVER_PORT:$NODE_PORT
    stdin_open: true
    tty: true

volumes: 
  db: